---
label: Project
hide_body: false
fields:
- type: text
  name: layout
  label: layout
  default: post
  config:
    required: true
  hidden: true
- type: text
  name: title
  label: Project Name
  config:
    required: true
- name: category
  type: select
  default: []
  config:
    required: true
    options:
    - United States
    - China
    - Oversea
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Category
- type: text
  name: location
  label: Detailed Location
- name: year
  type: datetime
  label: Year
  description: ''
  config:
    required: true
    date_format: YYYY
    time_format: 
    display_utc: false
    export_format: YYYY
- type: text
  name: site_area
  label: Size of the site
- type: text
  name: award
  label: Awards
