---
label: Project
hide_body: false
fields:
- type: text
  name: layout
  label: layout
  default: post
  config:
    required: true
  hidden: true
- type: text
  name: title
  label: Project Name
  config:
    required: true
- name: category
  type: select
  default: []
  config:
    required: true
    options:
    - United States
    - China
    - Oversea
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Category
- type: text
  name: location
  label: Detailed Location
- type: text
  name: site_area
  label: site_area
- type: number
  name: year
  label: year
- type: text
  name: award
  label: award
